-- ==============================================================================
-- WhereWasI? - Database Schema with Authentication, Social Friendships & RLS
--
-- WHERE TO RUN
--   Supabase Dashboard -> SQL Editor (or Supabase CLI)
--
-- IDEMPOTENT & SAFE TO RE-RUN
--   Every statement uses IF NOT EXISTS / OR REPLACE / DROP ... IF EXISTS.
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- ==============================================================================
-- 1. PROFILES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  username TEXT,
  display_name TEXT,
  avatar_url TEXT,
  bio TEXT DEFAULT '',
  approved BOOLEAN NOT NULL DEFAULT TRUE,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS approved BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles(LOWER(username)) WHERE username IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(LOWER(email));

-- ==============================================================================
-- 2. FRIENDSHIPS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.friendships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  addressee_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'declined', 'blocked')) DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT check_friendship_not_self CHECK (requester_id != addressee_id)
);

ALTER TABLE public.friendships ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE public.friendships ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Ensure pair is unique regardless of who requested
CREATE UNIQUE INDEX IF NOT EXISTS idx_friendships_unique_pair
  ON public.friendships (LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id));

CREATE INDEX IF NOT EXISTS idx_friendships_requester ON public.friendships(requester_id);
CREATE INDEX IF NOT EXISTS idx_friendships_addressee ON public.friendships(addressee_id);
CREATE INDEX IF NOT EXISTS idx_friendships_status ON public.friendships(status);

-- Helper function: Check if two users are confirmed friends
CREATE OR REPLACE FUNCTION public.are_friends(u1 UUID, u2 UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.friendships
    WHERE status = 'accepted'
      AND (
        (requester_id = u1 AND addressee_id = u2)
        OR
        (requester_id = u2 AND addressee_id = u1)
      )
  );
$$;

-- ==============================================================================
-- 3. MEDIA ITEMS (Series, Books, Movies, Anime, Manga, etc.)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.media_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  title TEXT NOT NULL,
  media_type TEXT NOT NULL CHECK (media_type IN ('series', 'book', 'movie', 'anime', 'manga', 'game', 'podcast', 'other')),
  status TEXT NOT NULL CHECK (status IN ('in_progress', 'completed', 'planned', 'on_hold', 'dropped')) DEFAULT 'in_progress',
  progress_type TEXT NOT NULL CHECK (progress_type IN ('episode_season', 'pages', 'percentage', 'chapter', 'custom')) DEFAULT 'episode_season',
  
  -- Progress counters
  season INT DEFAULT 1,
  episode INT DEFAULT 0,
  total_seasons INT,
  total_episodes INT,
  current_page INT DEFAULT 0,
  total_pages INT,
  percentage INT CHECK (percentage >= 0 AND percentage <= 100),
  current_unit TEXT,
  
  -- Rating & notes
  rating NUMERIC(3, 1) CHECK (rating >= 0 AND rating <= 10),
  review TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  cover_url TEXT,
  tags TEXT[] DEFAULT '{}',
  genre TEXT DEFAULT '',
  
  -- Flags & timestamps
  is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
  is_private BOOLEAN NOT NULL DEFAULT FALSE,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS media_type TEXT NOT NULL DEFAULT 'series';
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'in_progress';
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS progress_type TEXT NOT NULL DEFAULT 'episode_season';
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS season INT DEFAULT 1;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS episode INT DEFAULT 0;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS total_seasons INT;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS total_episodes INT;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS current_page INT DEFAULT 0;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS total_pages INT;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS percentage INT;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS current_unit TEXT;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS rating NUMERIC(3, 1);
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS review TEXT DEFAULT '';
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS cover_url TEXT;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS genre TEXT DEFAULT '';
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE public.media_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_media_user_id ON public.media_items(user_id);
CREATE INDEX IF NOT EXISTS idx_media_type ON public.media_items(media_type);
CREATE INDEX IF NOT EXISTS idx_media_status ON public.media_items(status);
CREATE INDEX IF NOT EXISTS idx_media_updated ON public.media_items(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_media_favorite ON public.media_items(is_favorite) WHERE is_favorite = TRUE;

-- ==============================================================================
-- 4. MEDIA ACTIVITIES (Social Feed / Updates)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.media_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  media_item_id BIGINT REFERENCES public.media_items(id) ON DELETE CASCADE,
  media_title TEXT NOT NULL,
  media_type TEXT NOT NULL,
  action_type TEXT NOT NULL, -- 'started', 'progress_updated', 'completed', 'rated', 'status_changed'
  progress_text TEXT,
  message TEXT,
  is_private BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.media_activities ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();
ALTER TABLE public.media_activities ADD COLUMN IF NOT EXISTS media_item_id BIGINT REFERENCES public.media_items(id) ON DELETE CASCADE;
ALTER TABLE public.media_activities ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_activities_user ON public.media_activities(user_id);
CREATE INDEX IF NOT EXISTS idx_activities_created ON public.media_activities(created_at DESC);

-- ==============================================================================
-- 5. AUTOMATIC TRIGGERS (Updated at & Profile sync)
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_profiles_updated ON public.profiles;
CREATE TRIGGER on_profiles_updated
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS on_media_updated ON public.media_items;
CREATE TRIGGER on_media_updated
  BEFORE UPDATE ON public.media_items
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS on_friendships_updated ON public.friendships;
CREATE TRIGGER on_friendships_updated
  BEFORE UPDATE ON public.friendships
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- Trigger to automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  extracted_username TEXT;
  extracted_display TEXT;
BEGIN
  extracted_username := COALESCE(
    NEW.raw_user_meta_data->>'username',
    SPLIT_PART(NEW.email, '@', 1)
  );
  extracted_display := COALESCE(
    NEW.raw_user_meta_data->>'display_name',
    SPLIT_PART(NEW.email, '@', 1)
  );

  INSERT INTO public.profiles (id, email, username, display_name, avatar_url, approved, is_admin)
  VALUES (
    NEW.id,
    NEW.email,
    extracted_username,
    extracted_display,
    NEW.raw_user_meta_data->>'avatar_url',
    TRUE,
    FALSE
  )
  ON CONFLICT (id) DO UPDATE
  SET
    email = EXCLUDED.email,
    username = COALESCE(public.profiles.username, EXCLUDED.username),
    display_name = COALESCE(public.profiles.display_name, EXCLUDED.display_name);

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================================================
-- 6. ROW LEVEL SECURITY (RLS)
-- ==============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_activities ENABLE ROW LEVEL SECURITY;

-- 6.1 Profiles Policies
DROP POLICY IF EXISTS "Anyone authenticated can view profiles" ON public.profiles;
CREATE POLICY "Anyone authenticated can view profiles"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- 6.2 Friendships Policies
DROP POLICY IF EXISTS "Users can view their friendships" ON public.friendships;
CREATE POLICY "Users can view their friendships"
  ON public.friendships FOR SELECT
  TO authenticated
  USING (auth.uid() = requester_id OR auth.uid() = addressee_id);

DROP POLICY IF EXISTS "Users can create friend requests" ON public.friendships;
CREATE POLICY "Users can create friend requests"
  ON public.friendships FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = requester_id);

DROP POLICY IF EXISTS "Users can update their friendships" ON public.friendships;
CREATE POLICY "Users can update their friendships"
  ON public.friendships FOR UPDATE
  TO authenticated
  USING (auth.uid() = requester_id OR auth.uid() = addressee_id)
  WITH CHECK (auth.uid() = requester_id OR auth.uid() = addressee_id);

DROP POLICY IF EXISTS "Users can delete their friendships" ON public.friendships;
CREATE POLICY "Users can delete their friendships"
  ON public.friendships FOR DELETE
  TO authenticated
  USING (auth.uid() = requester_id OR auth.uid() = addressee_id);

-- 6.3 Media Items Policies
DROP POLICY IF EXISTS "Users can view own items and friends non-private items" ON public.media_items;
CREATE POLICY "Users can view own items and friends non-private items"
  ON public.media_items FOR SELECT
  TO authenticated
  USING (
    auth.uid() = user_id
    OR
    (NOT is_private AND public.are_friends(auth.uid(), user_id))
  );

DROP POLICY IF EXISTS "Users can insert their own items" ON public.media_items;
CREATE POLICY "Users can insert their own items"
  ON public.media_items FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own items" ON public.media_items;
CREATE POLICY "Users can update their own items"
  ON public.media_items FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own items" ON public.media_items;
CREATE POLICY "Users can delete their own items"
  ON public.media_items FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- 6.4 Activities Policies
DROP POLICY IF EXISTS "Users can view own and friends activities" ON public.media_activities;
CREATE POLICY "Users can view own and friends activities"
  ON public.media_activities FOR SELECT
  TO authenticated
  USING (
    auth.uid() = user_id
    OR
    (NOT is_private AND public.are_friends(auth.uid(), user_id))
  );

DROP POLICY IF EXISTS "Users can insert own activities" ON public.media_activities;
CREATE POLICY "Users can insert own activities"
  ON public.media_activities FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- ==============================================================================
-- 7. RPC HELPER FUNCTIONS
-- ==============================================================================

-- Search user by email or username to send friend request
CREATE OR REPLACE FUNCTION public.send_friend_request_by_identifier(identifier TEXT)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_user RECORD;
  current_user_id UUID := auth.uid();
  existing_friendship RECORD;
  new_friendship_id BIGINT;
BEGIN
  IF current_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Non autenticato');
  END IF;

  identifier := LOWER(TRIM(identifier));

  IF identifier = '' THEN
    RETURN jsonb_build_object('success', false, 'error', 'Inserisci un nome utente o email valido');
  END IF;

  -- Find target profile
  SELECT * INTO target_user
  FROM public.profiles
  WHERE LOWER(email) = identifier OR LOWER(username) = identifier
  LIMIT 1;

  IF target_user.id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Utente non trovato');
  END IF;

  IF target_user.id = current_user_id THEN
    RETURN jsonb_build_object('success', false, 'error', 'Non puoi inviare una richiesta a te stesso');
  END IF;

  -- Check existing friendship
  SELECT * INTO existing_friendship
  FROM public.friendships
  WHERE (requester_id = current_user_id AND addressee_id = target_user.id)
     OR (requester_id = target_user.id AND addressee_id = current_user_id)
  LIMIT 1;

  IF existing_friendship.id IS NOT NULL THEN
    IF existing_friendship.status = 'accepted' THEN
      RETURN jsonb_build_object('success', false, 'error', 'Siete già amici!');
    ELSIF existing_friendship.status = 'pending' THEN
      IF existing_friendship.requester_id = current_user_id THEN
        RETURN jsonb_build_object('success', false, 'error', 'Hai già inviato una richiesta in attesa a questo utente');
      ELSE
        -- The other person already requested: automatically accept it!
        UPDATE public.friendships
        SET status = 'accepted', updated_at = NOW()
        WHERE id = existing_friendship.id;
        
        RETURN jsonb_build_object(
          'success', true,
          'message', 'Richiesta accettata! Ora siete amici.',
          'status', 'accepted',
          'friend', jsonb_build_object(
            'id', target_user.id,
            'email', target_user.email,
            'username', target_user.username,
            'display_name', target_user.display_name,
            'avatar_url', target_user.avatar_url
          )
        );
      END IF;
    ELSIF existing_friendship.status = 'declined' THEN
      -- Re-open request
      UPDATE public.friendships
      SET requester_id = current_user_id,
          addressee_id = target_user.id,
          status = 'pending',
          updated_at = NOW()
      WHERE id = existing_friendship.id;

      RETURN jsonb_build_object('success', true, 'message', 'Richiesta di amicizia inviata!', 'status', 'pending');
    END IF;
  END IF;

  -- Create fresh request
  INSERT INTO public.friendships (requester_id, addressee_id, status)
  VALUES (current_user_id, target_user.id, 'pending')
  RETURNING id INTO new_friendship_id;

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Richiesta di amicizia inviata con successo!',
    'status', 'pending',
    'friendship_id', new_friendship_id
  );
END;
$$;
